apiVersion: v1
kind: ConfigMap
metadata:
  name: codie-config
  namespace: collab
data:
  NODE_ENV: "production"
  PORT: "5000"
  REDIS_URL: "rediss://default:gQAAAAAAAQrMAAIgcDJkZjI5YWYyYTBkMDE0YWI0ODJlNzdjZjBjMTc3YjFmOQ@sure-skunk-68300.upstash.io:6379"
  PISTON_URL: "http://piston:2000"
  REFRESH_TOKEN_MAX_AGE: "604800000"
  RUN_BACKGROUND_JOBS: "true"
  CLIENT_URL: "http://localhost:3000"
  CORS_ORIGINS: "http://localhost:3000,http://localhost"
