apiVersion: v1
kind: Secret
metadata:
  name: codie-secrets
  namespace: collab
type: Opaque
stringData:
  DATABASE_URL: "mongodb+srv://pachu_codie:Pachucodie@codiecluster.nezlvor.mongodb.net/codie?appName=codieCluster"
  ACCESS_TOKEN_SECRET: "youraccesstokensecret"
  REFRESH_TOKEN_SECRET: "yourrefreshtokensecret"
  EMAIL_USER: "farazpachu777@gmail.com"
  EMAIL_PASS: "qgun ixox aref tmqz"
  GEMINI_API_KEY: "AIzaSyA5aAWhfMiWH1CF7FsMZRnXF47srMFi174"
  CLOUDINARY_API_KEY: "649738724331535"
  CLOUDINARY_CLOUD_NAME: "doi3h7fii"
  CLOUDINARY_SECRET: "dbJ1L3YqZllmF0ehKwNn8aZXAbg"
  RAZORPAY_KEY_ID: "rzp_test_kvk33t7GvztJdR"
  RAZORPAY_SECRET_ID: "otyaDCMXE4DTtkFJYWw2R0DA"
