version: "3.9"
services:
  app:
    build: .
    deploy:
      replicas: 3
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - redis
      - worker

  redis:
    image: redis:alpine
    networks:
      - backend

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/bullmq/schedulers/subscriptionScheduler.js
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/bullmq/workers/subscriptionWorker.js
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge
