version: "3.9"
services:
  app:
    build: .
    deploy:
      replicas: 2
    expose:
      - "5000"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - redis
      - worker

  redis:
    image: redis:alpine
    networks:
      - backend

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/bullmq/schedulers/subscriptionScheduler.js
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/bullmq/workers/subscriptionWorker.js
    env_file:
      - .env
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:80"  # map host:5000 → nginx:80
    depends_on:
      - app
    networks:
      - backend

networks:
  backend:
    driver: bridge
