version: "3.9"

services:
  app:
    build: .
    container_name: my-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
